# Generated by Django 5.2 on 2025-04-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specs',
        ),
        migrations.AddField(
            model_name='product',
            name='compatibility',
            field=models.TextField(blank=True, null=True, verbose_name='Совместимость'),
        ),
        migrations.AddField(
            model_name='product',
            name='installation',
            field=models.TextField(blank=True, null=True, verbose_name='Установка'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Вес комплекта'),
        ),
    ]
