name: Python Django Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: qwe
          POSTGRES_DB: nxt_sports_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Clear GitHub Actions Cache
      run: rm -rf ~/.cache/pip

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-django djangorestframework drf_yasg django-extensions==4.1.0

    - name: Run tests with pytest
      env:
        DATABASE_URL: postgres://postgres:qwe@localhost:5432/nxt_sports_db
      run: |
        pytest --junitxml=results.xml

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: results.xml
